chore: Add a bunch of formatters and linters
creativenull/efmls-configs-nvim pull request #19
Opened 2023-07-27 15:58 UTC by mrjones2014

Adds:

- cbfmt
- fish_indent
- gofmt
- nixfmt
- rustfmt
- statix

2023-07-27 15:59 UTC, mrjones2014 commented
I tried adding `fish --no-execute` as well but ran into some issues. It looks like `null-ls` has s[ome special processing on the output ](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/db09b6c691def0038c456551e4e2772186449f35/lua/null-ls/helpers/diagnostics.lua#L114) which I am not sure how to do with `efm-langserver`.

2023-07-28 01:22 UTC, creativenull requested changes

2023-07-28 01:22 UTC, creativenull commented on lua/efmls-configs/formatters/gofmt.lua
I don't think we need this because `gopls` already uses `gofmt` internally.

2023-07-28 01:22 UTC, creativenull commented on lua/efmls-configs/formatters/rustfmt.lua
Same as `gofmt` don't really need this when `rust-analyzer` is already able to do this.

2023-07-28 01:25 UTC, creativenull commented
> I tried adding `fish --no-execute` as well but ran into some issues. It looks like `null-ls` has s[ome special processing on the output ](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/db09b6c691def0038c456551e4e2772186449f35/lua/null-ls/helpers/diagnostics.lua#L114) which I am not sure how to do with `efm-langserver`.
> 
> Here's my (non-working) attempt:
> 
> ```lua
> -- TODO this isn't working
> local fs = require('efmls-configs.fs')
> local linter = fs.executable('fish')
> local command = string.format('%s --no-execute ${INPUT}', linter)
> 
> return {
>   lintCommand = command,
>   -- lintIgnoreExitCode = true,
>   lintStdin = false,
>   lintFormats = { '%f (line %l): %m' }, -- this doesn't work properly
> }
> ```

Do you have a test code that I can test it with? Either way this can be a separate PR.

2023-07-28 10:52 UTC, mrjones2014 commented
> Do you have a test code that I can test it with? 

I was testing it by just having an unmatched `end`, something like this:

```fish
function my-function
  ls .
# end # <-- note how the `end` is commented out
```

When `fish --no-execute` is run in the terminal, it produces output like this:

```
path/to/script.fish (line 5): Missing end to balance this function definition
function my-function
^~~~~~~^
warning: Error while reading file path/to/script.fish
```

2023-07-28 10:57 UTC, mrjones2014 commented on lua/efmls-configs/formatters/gofmt.lua
Does it hurt anything to keep it though? For consistency, I like to keep all my formatting going through a central system (previously null-ls, now efm-langserver).

It also solves a slight annoyance that comes up with user configs -- one example being tsserver supports formatting via LSP, but I want to format with prettier. In this case, Neovim will ask you to choose a server to format with. By having all my formatting all going through efm-langserver, I can just disable formatting for all servers except efm-langserver, and never have to worry about being asked which server to format with -- I always want to format with efm-langserver.

2023-07-28 10:57 UTC, mrjones2014 commented on lua/efmls-configs/formatters/rustfmt.lua
Same question as above. If you feel strongly about it I'm happy to remove it, but I don't think it hurts anything to keep it.

2023-07-28 14:26 UTC, creativenull commented on lua/efmls-configs/formatters/gofmt.lua
IMO its not great DX to have a completely different language server for formatting and linting when the main language server can do that. You're going to start getting inconsistency because lsp is doing one thing and then efm comes in and does it another way.

I would dynamically register the formatting capabilities (keymap or autoformat) so then it will work normally for lsp servers that can format and only use efm as a fallback ([this is how I currently do it](https://github.com/creativenull/dotfiles/blob/3ddb931a5036f312d1b2dfaaff1e11f396e63bb0/config/nvim/lua/user/lsp.lua#L22)).

But alas we don't live in a perfect world so this is fine for now xD

2023-07-28 14:27 UTC, creativenull approved these changes

2023-07-28 14:28 UTC, merged